[package]
name = "objektdb"
version = "0.1.0"
edition = "2024"

[dependencies]
objektdb_core = {path = "objektdb_core"}
objektdb_macros = {path = "objektdb_macros"}

[workspace]
members = [ "macro_support",
    "objektdb_core",
    "objektdb_macros"
]
