[package]
name = "objektdb_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
objektdb_core = {path = "../objektdb_core"}
proc-macro2 = { version = "1.0", features = ["span-locations"] }

[lib]
proc-macro = true