[package]
name = "objektdb_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
core = {path = ../objektdb_core}

[lib]
proc-macro = true